-- Supabaseにテーブルを作成するSQLスクリプト

-- 商品マスターテーブル
CREATE TABLE IF NOT EXISTS product_master (
    PRD_ID SERIAL PRIMARY KEY,
    CODE BIGINT UNIQUE NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    PRICE INTEGER NOT NULL
);

-- 取引テーブル
CREATE TABLE IF NOT EXISTS transaction (
    TRD_ID SERIAL PRIMARY KEY,
    DATETIME TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EMP_CD VARCHAR(10) DEFAULT '9999999999',
    STORE_CD VARCHAR(5) DEFAULT '30',
    POS_NO VARCHAR(3) DEFAULT '90',
    TOTAL_AMT INTEGER DEFAULT 0,
    TTL_AMT_EX_TAX INTEGER DEFAULT 0
);

-- 取引詳細テーブル
CREATE TABLE IF NOT EXISTS transaction_detail (
    TRD_ID INTEGER REFERENCES transaction(TRD_ID),
    DTL_ID INTEGER,
    PRD_ID INTEGER REFERENCES product_master(PRD_ID),
    PRD_CODE VARCHAR(13) NOT NULL,
    PRD_NAME VARCHAR(50) NOT NULL,
    PRD_PRICE INTEGER NOT NULL,
    TAX_CD VARCHAR(2) DEFAULT '10',
    PRIMARY KEY (TRD_ID, DTL_ID)
);

-- サンプルデータの挿入（オプション）
INSERT INTO product_master (CODE, NAME, PRICE) VALUES 
(1234567890123, 'コーラ', 150),
(1234567890124, 'お茶', 120),
(1234567890125, 'チョコレート', 200)
ON CONFLICT (CODE) DO NOTHING; 